name: Deploy static site to S3

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync HTML and root (short cache)
        run: |
          aws s3 sync dist s3://$S3_BUCKET             --delete             --exclude "assets/*"             --cache-control "public,max-age=300"

      - name: Sync versioned assets (long cache)
        run: |
          aws s3 sync dist/assets s3://$S3_BUCKET/assets             --delete             --cache-control "public,max-age=31536000,immutable"

      - name: Create CloudFront invalidation (optional)
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation             --distribution-id $CLOUDFRONT_DISTRIBUTION_ID             --paths "/*"
